### POST struct/request test by RestClient of vscode extenstion
POST http://127.0.0.1:9881/struct/request/zhangsan?money=1000
Content-Type: application/json
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: Authorization=auth123123;

{
    "replicas":5
}

### POST  struct/nested test by RestClient of vscode extenstion
POST http://127.0.0.1:9881/struct/nested/zhangsan/666?money=1000
Content-Type: application/json
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: Authorization=auth123123;

{
    "replicas":5
}

### GET struct/nested test by RestClient of vscode extenstion
### GET 请求的特殊性
##### 1. 在 server 端没有默认指定 body 读取方式的时候。 通常会以 JSON 方式读取。
##### 2. 但是 GET 请求则必须使用 Form 方式。
##### 继承自 gin/binding/binding.go， Default() 函数中是这样规定的
GET http://127.0.0.1:9881/struct/nested/zhangsan/666?money=1000
Content-Type: application/json
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: Authorization=auth123123;

{
    "replicas":5
}

### POST  mime/json test by RestClient of vscode extenstion
POST http://127.0.0.1:9881/mime/json/zhangsan?money=1000
Content-Type: application/json
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: Authorization=auth123123;

{
    "replicas":5
}


### GET mime/json test by RestClient of vscode extenstion
GET http://127.0.0.1:9881/mime/json/zhangsan?money=1000
# Content-Type: application/json
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
Cookie: Authorization=auth123123;

{
    "replicas":5
}


### GET Without Body mime/json test by RestClient of vscode extenstion
GET http://127.0.0.1:9881/mime/json/zhangsan?money=1000



### POST form
POST http://127.0.0.1:9881/mime/postform/zhangsan?money=1000
Content-Type: application/x-www-form-urlencoded

replicas=102&resourceId=acs%3Acms%3A%3A5719900881055885%3Acontact%2FADD-DevOps&product=CloudMonitor&ver=1.0&instanceName=ADD-DevOps&level=INFO&groupId=&eventType=Alert&userId=5719900881055885&content=%7B%22param%22%3A%7B%7D%2C%22source%22%3A%22unknown%22%2C%22detail%22%3A%7B%22ruleName%22%3A%22xxxxxx%22%2C%22title%22%3A%22yyyyyyy%22%2C%22message%22%3A%22zzzzzz%22%7D%7D&regionId=cn-hangzhou&eventTime=20221026T114505.863%2B0800&name=AlertWebHook&ruleName=SYS_EVENT_CloudMonitor_AlertWebHook&id=c1cda5a2-4bcd-466d-a628-0321ff750dcf&status=Alarm
